package goji;

import javax.persistence.*;
import java.util.Objects;

//Class used to specify entity to represent Messages on the system
//messageID is autogenerated ID used for retrieving messages from storage, and forcing some uniqueness between message. Spec does not specify what a message contains,
// so I chose not to assume that it would include a field that could uniquely identify messages
//contents is the actual message that the user is sending. Bare minimum a message should contain this
//userID represents a use. Users in the system do not have their own class/entity as only an identifier was necessary for the purposes of this exercise.
//I chose a String as usernames typically have at least a few no numeric characters
@Entity
public class Message {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Long messageID;
    private String userID;
    private String contents;

    public Message() {
        super();
    }

    Message(String userID, String contents) {
        this.userID = userID;
        this.contents = contents;
    }

    public Long getMessageID() {
        return messageID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getContents() {
        return contents;
    }

    public void setContents(String contents) {
        this.contents = contents;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return Objects.equals(messageID, message.messageID) &&
                Objects.equals(userID, message.userID) &&
                Objects.equals(contents, message.contents);
    }

    @Override
    public int hashCode() {

        return Objects.hash(messageID, userID, contents);
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageID=" + messageID +
                ", userID='" + userID + '\'' +
                ", contents='" + contents + '\'' +
                '}';
    }
}
